@startuml
title Diagrama de Paquetes - Simulador de Inversiones en Criptomonedas

package "Presentacion" {
  [Login/Registro]
  [Dashboard]
  [Mercado]
  [Detalle/Trading]
  [Portafolio]
  [Historial]
  [Conversion Cripto]
}

package "Logica de Negocio" {
  [Powerapp]
  [Validaciones]
  [Calculos]
}

package "Datos" {
  [sharepoints]
  [API Precios]
}

package "Componentes" {
  [compTabBar]
}

Presentacion --> "Logica de Negocio"
Presentacion --> Componentes
"Logica de Negocio" --> Datos

@enduml
